CREATE DATABASE customer_behavior;

USE customer_behavior;

SELECT * FROM customer;

-- 1 what is the total revenue Generated by the Male and Female Customers
select  gender, sum(purchase_amount) as revenue from customer
group by gender;

-- 2 which customer used discount but still used more than average purchase amount
select customer_id,purchase_amount from customer
where discount_applied ="Yes" and purchase_amount >= (select avg(purchase_amount) from customer);

-- 3 which are the top 5 products with average highest rating

select item_purchased ,avg(review_rating) as avg_rating from customer
group by item_purchased
order by avg_rating desc
limit 5;

-- 4 compare the average purchase amount  between standard and express shiping
select shipping_type , avg(purchase_amount) as avg_pur_amount 
from customer
where shipping_type in ("Express" , "Standard")
group by shipping_type;

-- 5- do subscriberd customer spend more  -- 
-- compare average spend and total revenue between subscriber and non subscriber
select avg(purchase_amount) as avg_spent, 
sum(purchase_amount) as total_rev, 
subscription_status,
count(customer_id) as total_customer
from customer
group by subscription_status;

-- 6 which 5  products have the Highest percentage of purchase with discount applied
SELECT
    item_purchased,
    COUNT(*) AS total_purchases,
    ROUND(
        COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number 
-- of previous purchases, and show the count of each segment.
USE customer_behavior;

SELECT
    CASE
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_type,
    COUNT(*) AS total_customers
FROM customer
GROUP BY customer_type;

-- 8 what are the top 3 most purchase product of each category
select item_purchased as most_purchase,
COUNT(*) as total_purchase
from customer
group by item_purchased
order by total_purchase  desc
limit 3;

-- 9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS total_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10 What is the revenue contribution of each age group?
SELECT
    age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

SELECT @@hostname,
       @@port,
       DATABASE();

SELECT * FROM customer LIMIT 5;